# DL via ANN

## Importing libraries

In [54]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [55]:
tf.__version__

'2.17.0'

## Importing dataset

In [56]:
dataset= pd.read_csv('American_Express_User_Exit_Pred.csv')
X= dataset.iloc[:, 0:-1].values
y= dataset.iloc[:, -1].values

In [57]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


## Encoding Categorical Data 

### General column: Label Encoding

In [58]:
from sklearn.preprocessing import LabelEncoder
label_encoder= LabelEncoder()
X[:, 2]= label_encoder.fit_transform(X[:, 2])

In [59]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


## Geography column : Label Encoding

In [60]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder= 'passthrough')
X= np.array(ct.fit_transform(X))

In [61]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


## Splitting the dataset into Training & Test Set

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size= 0.2, random_state= 0)

## Feature Scaling

In [63]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.fit_transform(X_test)


# ANN

## Initialization 

In [64]:
ann= tf.keras.models.Sequential()

## Adding input layer and first hidden layer

In [65]:
ann.add(tf.keras.layers.Dense(units=5, activation= 'relu'))

## Adding second hidden layer

In [66]:
ann.add(tf.keras.layers.Dense(units=5, activation= 'relu'))

## Adding output layer

In [67]:
ann.add(tf.keras.layers.Dense(units=1, activation= 'sigmoid'))

# ANN Training

## Compiling ANN

In [68]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

## Training on training dataset

In [69]:
ann.fit(X_train, y_train_one_hot, batch_size= 32, epochs=120)

Epoch 1/120


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 5), output.shape=(None, 1)

In [ ]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]]))>0.5)

In [ ]:
y_test_one_hot = to_categorical(y_test, num_classes=5)

In [ ]:
y_pred=ann.predict(X_test)
y_pred=(y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test_one_hot.reshape(len(y_test),1)),1))